apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-run
spec:
  template:
    spec:
      containers:
      - name: pipeline-container
        image: eisokant/pipeline
        command: ["pipeline", "--onDocker", "/data"]
      restartPolicy: Never
